### ISSUE TITLE
Item Deposit

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#100]
**Requirements:** 

Updated Nov 14:

As a regular user I want to:

- [x] Describe an item #252 
- [x] Assign a license and any embargo necessary #253 
- [x] Upload files and move into desired order https://github.com/ualbertalib/jupiter/issues/254
- [x] Agree to terms of use https://github.com/ualbertalib/jupiter/issues/255
- [x] Deposit an item into ERA https://github.com/ualbertalib/jupiter/issues/255
- [x] Generate thumbnail when depositing an item into ERA #19 
- [x] create sort_year based on during item deposit #166 

(Above is in scope for the draft feature release)

(Below is out of scope for the draft feature release #269 )
- [ ] Proper file ordering https://github.com/ualbertalib/jupiter/issues/362

As an Admin user, I want to do everything a regular user can do, AND:

- [x] Create CCID authenticated items https://github.com/ualbertalib/jupiter/issues/269 
- [x] Create private items (replaced with draft item)

Move Thesis deposit into a separate ticket. 

**Notes:**

- Admin deposit is the same as regular user, EXCEPT: Admin can deposit thesis, admin can see additional visibility options, admin does NOT need to see Deposit Agreement in last step.
- Fields for drop-down menus, etc should come from data dictionary
- language for help ? buttons is here: https://docs.google.com/document/d/1qSMwRoNfyPt6aVZAkP-9dh9sgfWRSzuRRWHLLvvYnjM/edit
  - We should make these help text under the inputs where makes sense instead of a tooltip (tooltips dont work nicely on mobile etc)
- language for Deposit and Distribution Agreement is here: https://docs.google.com/document/d/1yD3hLShEY2JlaGpWxvTMEdcOTqQxYwgWiqMczl9lRbw/edit

**Form Design Checklist**

- [ ] Does my form have any repeated actions?
- [ ] Does my form only have fields that are necessary?
- [ ] Can any of the fields in my form be pre-filled?
- [ ] Does my form provide progress bars and menus to indicate overall progress
- [ ] Does my form choose the most appropriate input type for data to simplify input? (See also  9241-161: Guidance on Visual User Interface Elements and HTML 5 Input Types
- [ ] Have I grouped similar elements (such as checkboxes or radio buttons) together using <fieldset> on my form?
- [ ] Does my form offer autocomplete when appropriate?
- [ ] Does my form provide hint to users about what’s expected in the input? (such as with placeholder)
- [ ] Does my form provide data validation, preferably real-time data validation?
- [ ] Does my form provide clear error messages (that are accessible)? Does my form provided easy ways for users to identify their errors and to fix them?
- [ ] Does my form provide appropriate feedback to users on form actions?

**Wireframes:**

- Describe item: 
![Image of Describe item Mockup](https://jupiter.mybalsamiq.com/mockups/6148333.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Deposit%20-%20Describe%20item
- Choose a license:
![Image of Choose a license Mockup](https://jupiter.mybalsamiq.com/mockups/6172846.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Deposit%20-%20Choose%20a%20license
- Upload items:
![Image of Upload items Mockup](https://jupiter.mybalsamiq.com/mockups/6172847.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Deposit%20-%20Upload%20files
- Review and add items to ERA: 
![Image of Search Mockup](https://jupiter.mybalsamiq.com/mockups/6172848.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Deposit%20-%20Review%20and%20add
- Deposit a thesis: 
![Image of Deposit Thesis Mockup](https://jupiter.mybalsamiq.com/mockups/6178693.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Deposit%20-%20Thesis

**Comment by sfbetz** [comment]
@leahvanderjagt review and pls confirm when language for Deposit agreement is finalized.

**Comment by murny** [comment]
Mockups now embeded (images will always be updated with latest mockups)

**Comment by murny** [comment]
Closing out. Been in production for awhile
