### ISSUE TITLE
Front Page / Theme

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#101]
To-do:
- [ ] Footer, with sticky footer so it always stays at the bottom of the page (https://getbootstrap.com/docs/4.0/examples/sticky-footer/)
- [ ] Header, should be a fixed nav bar so it moves when scrolling down the page
(http://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/)
- [ ] Search box not to fold into menu on mobile design
- [ ] feature collections with no images on mobile

Mockup:
![Image of Homepage Mockup](https://jupiter.mybalsamiq.com/mockups/6239680.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Homepage

**Mockups from Natasha** (Wireframe takes precedences if there are any discrepancy between mockups and wireframes)
Home page:
![jupiter-mockup-first-edit](https://user-images.githubusercontent.com/2047614/35065036-3002cc42-fb89-11e7-9c2b-de3754a84c01.jpg)
Home page mobile:
![jupiter-home-mobile](https://user-images.githubusercontent.com/2047614/35065033-2de717ba-fb89-11e7-8813-c4e3b4d4a96d.jpg)
Secondary page:
![jupiter-secondary](https://user-images.githubusercontent.com/2047614/35065050-33d9737a-fb89-11e7-8405-06499ebd6edc.jpg)
Secondary page mobile:
![jupiter-secondary-mobile-](https://user-images.githubusercontent.com/2047614/35065042-31bb758e-fb89-11e7-8c7c-197f9a8d49a2.jpg)

Banner Image:
![banner](https://user-images.githubusercontent.com/2047614/35065060-3db16bdc-fb89-11e7-9511-b52f1dee1a65.jpg)
Please let Sonya know if higher resolution of the image is needed. 

Font:
Suggestion from Natasha:
The font for the logo and headings is Playfair Display from google fonts https://fonts.google.com/specimen/Playfair+Display. The rest of the fonts are Helvetica, but can be substituted for system sans-serif fonts. 
We will try to use system fonts whenever possible, for consistency and performance purpose. 

Color:
#dbe1ef

**Comment by weiweishi** [comment]
Questions
- [ ] Explore our collections/communities
- [ ] text for Welcome to ERA
- [ ] Change to Browse? Additional browsing all?
