### ISSUE TITLE
Item edit history for admin users

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1262]
**Is your feature request related to a problem? Please describe.**
As an admin user, I would like to see edit history of an item, including:
- when the object is deposited, by who
- edit history of the object, who edited the object at what time, or when new version of the file is uploaded. 
In the future, we'd like to see the preservation history of the object as well, but @weiweishi thinks this should belong to the admin dashboard for our single-source-of-truth. 

Initial work required:
- [x] Wireframe with @abombak to design how the information can be presented on the record view
   We must capture:
   - When edit was done
   - Who did it (email is the most useful)
   - What was changed (include changes made to any item properties)
- [x] whiteboarding data structure/model needed to support the edit history, what information is already available, what additional information we'd need to capture.
  - not needed as once were off fedora we'll just be using the papertrail gem which handles this
- [ ] get @ualbertalib/metadata-team's opinion on additional information that would support their work. and how the data needs to be reflected in our data dictionary. 

Issues in this epic:
- [ ] Set up papertrail gem #1363
- [ ] Create current_user methods for papertrail #1364
- [ ] Set up admin view of papertrail edit history #1365

**Comment by mbarnett** [comment]
Dropping a link here for when it comes time to look at implementation details: https://github.com/paper-trail-gem/paper_trail

**Comment by mbarnett** [comment]
This is now implemented and (finally) live.
