### ISSUE TITLE
Rails 6 Upgrade

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1287]
We should upgrade to Rails 6 ahead in anticipation of any further work on Jupiter, so that we don't end up doing more work tied to an older version that is eventually going to fall out of support.

### Impact on Dependencies

- Rails 6 is dropping support for PostgreSQL < 9.3 -- Production is currently 9.2.24. The latest version of 11.5, and 12 is in beta. Ideally we'd like to move to something in the PostgreSQL 11 series to take advantage of more robust (and more performant) JSON support.

- Need to double-check that there are no other important gems roadblocking this

## Upgrading from Rails 5.2 to Rails 6.0
- Upgrade to Webpacker, Remove Sprockets/Asset Pipeline (Could come later, can run Rails 6 on Asset Pipeline/Sprockets) (https://github.com/ualbertalib/jupiter/issues/207)
  - Remove any javascript/css gems in favor for NPM packages (fontawesome, bootstrap, selectize, etc)
  - Move Assets code to Javascript folder
  - Rename a few link/script/image tag helpers in view files
  - Rewrite Javascript using ES6
  - Enable Eslint/StyleLint
- Autoloading changes (Zeitwerk)
  - May require some work here. We can opt in for old behaviour to ease upgrade pains.
  - Check compatibility of Zeitwerk with jupiter via `$ bin/rails zeitwerk:check`
  - No longer need `require_dependency`
 - Active Storage assignment behavior change
   - ActiveStorage now aligns itself more closer to ActiveRecord behaviour. Assigning a collection to has_many_attachments will now override the existing attachments instead of appending.
- New features
  -  Action Text - a rich text content and editing to Rails. It includes the Trix editor that handles everything from formatting to links to quotes to lists to embedded images and galleries. (Could be useful for text areas or editing static pages: https://github.com/ualbertalib/jupiter/issues/39#issuecomment-453254512)
  - Parallel Testing - allows you to parallelize your test suite. While forking processes is the default method, threading is supported as well. Running tests in parallel reduces the time it takes your entire test suite to run.

More info: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0

## Subtasks

- [x] #1430 Upgrade Rails gem to latest v6.x
- [x] #1431 Transition to Webpacker from Sprockets
- [x] #1432 Transition to Zeitwerk for Autoloading
- [ ] #1433 Upgrade Infrastructure for Rails 6

**Comment by mbarnett** [comment]
In production (just in time for 6.1 haha)
