### ISSUE TITLE
Align Ourselves With the Data Dictionary

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#165]
Updated Jan 3, 2018: To do:

- [x] every element in the data dictionary is brought into line for Item #251 
- [x] every element in the data dictionary is brought into line for thesis object #335 
- [x] expand license's controlled vocabulary. https://github.com/ualbertalib/jupiter/issues/356

Completed:
- [x] every element in the data dictionary is brought into line for Collection
- [x] every element in the data dictionary is brought into line for Community

The current Item properties were just a slapped together mess created for the demo. Chris has kindly volunteered to take this off my plate, work through the data dictionary, open tickets for all of the unclear elements in the metadata repository, and make sure everything is brought cleanly into line. Zach is putting together a list of questions about how current ERA works and how that should relate to the way Jupiter works long-term, which should help inform this process, so this will involve sitting down with him to work through his questions and make sure our PCDM modelling reflects metadata's understanding. 

Since we're doing this now, instead of waiting until the upload sprint, we're probably going to have to do this a few times instead of once-and-done. 

- [ ] every element in the data dictionary is brought into line for Item #251 
- [ ] every element in the data dictionary is brought into line for Collection
- [ ] every element in the data dictionary is brought into line for Community
- [ ] decisions made in Jupiter are fed back into the data dictionary (predicates etc for elements, temporary namespaced "system" properties we need a proper namespace and predicated for, etc)
- [ ] rdf:types and other base Fedora stuff in-line with what Metadata is expecting (ie rdf:type on Community is currently incorrect)
- [ ] Zach's questions fully answered
- [ ] No further unclarity in the data dictionary wrt required fields, May vs Should vs Must, how we're dealing with facets, etc.

It will probably be useful to add subtickets to this as the task evolves, so I'm making this an epic to facilitate that.
