### ISSUE TITLE
Data Migration Testing & Fixup

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1685]
### Tasks

- [x] Give Henry heads up that we're going to be testing this
- [x] Connor sends me his public key so I can set up the tunnel
- [x] Fix known date issue on stage1 branch (see below). 
- [x] Fix record_created_at issue on stage1 branch (see below). 
- [x] Address https://github.com/ualbertalib/jupiter/pull/1272#discussion_r364950912 (this will also need to be fixed on postmigration)
- [x] Create tunnel for Connor
    - [x] SSH keys (gen new on my machine, Connor hand off to Henry)
- [x] Tag a new release of stage1 with the fix and get Henry to deploy it to the new staging server
- [x] Get into the new staging server
- [x] Ensure stage1 is deployed on server
- [x] Run migration rake task
- [x] If it errors out, fix any new errors
- [x] Get Henry to restore Solr to its pre-migration state
- [x] Clean out Postgresql
- [x] Re-Run migration
- [x] Rinse & Repeat
- [x] Once we have this working, tag a new release of integration_postmigration and get him to deploy it to the new staging app server. Migrations will need to be run
- [x] All data should now be migrated, thoroughly test that everything is working in the new environment

### Known Date Issue

Legacy theses have a four-digit `date_accepted` field instead of a full date, which blows up when we try to migrate those theses into the postgres column, which is type date. The decision from metadata was that this is an optional field, so for this legacy data we can simply blank this attribute out during the migration, if we detect that the thesis has a four character `date_accepted` (or more broadly, any invalid `date_accepted`). Probably the best way to fix this would be in `from_thesis`, here: https://github.com/ualbertalib/jupiter/blob/integration_migration_phase1/lib/tasks/jupiter.rake#L111.

### Known record_created_at issue

We track when a record was first created in Jupiter on a recordCreatedInJupiter predicate that corresponds to the attribute `record_created_at`.  We set that here: https://github.com/ualbertalib/jupiter/blob/4a220575d1dbb45af4e3f3a2b03dde5fa9ea6f6c/app/models/jupiter_core/depositable.rb#L140. Normally this is fine, but when we're migrating this data we don't want to override the data coming out of ActiveFedora with a new "recordCreateInJupiter" time for their ActiveRecord version; we need to preserve the original date.

**Note that any fixes to the above will need to merge into the stage 1 branch and then separately into postmigration if we want to keep them around post-deployment.**

**Comment by ConnorSheremeta** [comment]
`time RAILS_ENV=staging rake jupiter:get_me_off_of_fedora` failed after only 3 seconds
```
W, [2020-06-29T15:37:32.245638 #13701]  WARN -- Skylight: [SKYLIGHT] [4.1.2] You are running in the staging environment but haven't added it to config.skylight.environments, so no data will be sent to Skylight servers.

Preparing Draft Item ...
..........................................................................................................................................................................rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Blob must exist
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:52:in `save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `block in save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:48:in `save!'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:62:in `block (4 levels) in <top (required)>'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:60:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:59:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora
(See full trace by running task with --trace)

real	0m3.545s
user	0m2.109s
sys	0m0.274s
```

`ActiveRecord::RecordInvalid: Validation failed: Blob must exist` was thrown when preparing draft items, looking into this now.

**Comment by ConnorSheremeta** [comment]
Second error:

Migrating Communities...
rake aborted!
ArgumentError: Community 6a21c1d8-842d-40c7-81f3-e3e2b924a328 already migrated
/var/www/sites/jupiter/app/models/ar_community.rb:9:in `from_community'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:87:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:118:in `block in each'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `map'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:86:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora
(See full trace by running task with --trace)

real	0m3.111s
user	0m2.250s
sys	0m0.247s


Third error:
Migrating Collections...
rake aborted!
ArgumentError: Collection d3a71855-d041-49b3-82f5-4aa68157ec90 already migrated
/var/www/sites/jupiter/app/models/ar_collection.rb:12:in `from_collection'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:95:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:118:in `block in each'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `map'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:94:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora
(See full trace by running task with --trace)

real	0m2.084s
user	0m1.691s
sys	0m0.206s

Fourth error:
Migrating Items...
rake aborted!
ArgumentError: Item b36916e6-7449-45db-8a8a-6ccce2641e73 already migrated
/var/www/sites/jupiter/app/models/ar_item.rb:96:in `from_item'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:103:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:118:in `block in each'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `map'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:102:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora
(See full trace by running task with --trace)

real	0m9.632s
user	0m3.548s
sys	0m0.409s


______ already migrated is the theme here. Maybe the rake task has been ran previously and postgres needs to be cleaned out before running this again.

**Comment by ConnorSheremeta** [comment]
Cleaned out postres tables ArCommunity, ArCollection, ArItem, and ArThesis.

```
 Migrating Communities...
........................rake aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "unique_active_storage_attachment"
DETAIL:  Key (record_type, record_id, name, blob_id)=(ArCommunity, 0, logo, 44349) already exists.

```
Cleared out active_storage_attachments and active_storage_blobs and tried again...

```
Migrating Items...
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................rake aborted!
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on table "ar_items" violates foreign key constraint "fk_rails_0a52c372f9"
DETAIL:  Key (owner_id)=(3523) is not present in table "users".
: INSERT INTO "ar_items" ("id", "visibility", "owner_id", "record_created_at", "date_ingested", "title", "doi", "sort_year", "member_of_paths", "subject", "creators", "created", "spatial_subjects", "languages", "license", "item_type", "aasm_state", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id"
```

Got further that time. It looks like the owner (id=3523) is not currently in the user table, looking into why that is.

**Comment by ConnorSheremeta** [comment]
Now faking the owner_id.

```
Migrating Theses...
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................rake aborted!
ArgumentError: argument out of range
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `initialize'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `new'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `parts_to_time'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:416:in `parse'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:508:in `coerce_value'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:476:in `coerce_value'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:741:in `block in define_cached_reader'
/var/www/sites/jupiter/app/models/ar_thesis.rb:108:in `block in from_thesis'
/var/www/sites/jupiter/app/models/ar_thesis.rb:107:in `each'
/var/www/sites/jupiter/app/models/ar_thesis.rb:107:in `from_thesis'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:111:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:118:in `block in each'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116[2000]:in `map'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:110:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora
```

More issues in coerce_value. The offending date this time is 'c1984'. Ignored values of length 5...

`rake aborted!
ArgumentError: argument out of range
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `initialize'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `new'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `parts_to_time'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:416:in `parse'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:509:in `coerce_value'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:476:in `coerce_value'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:742:in `block in define_cached_reader'
/var/www/sites/jupiter/app/models/ar_thesis.rb:109:in `block in from_thesis'
/var/www/sites/jupiter/app/models/ar_thesis.rb:108:in `each'
/var/www/sites/jupiter/app/models/ar_thesis.rb:108:in `from_thesis'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:111:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:118:in `block in each'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `map'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:110:in `block (2 levels) in <top (required)>'
`

Same error, offending date now is '[2000]'... ignoring values of length 6 now.


`ArgumentError: argument out of range
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `initialize'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `new'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:543:in `parts_to_time'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/values/time_zone.rb:416:in `parse'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:509:in `coerce_value'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:476:in `coerce_value'
/var/www/sites/jupiter/app/models/jupiter_core/locked_ldp_object.rb:742:in `block in define_cached_reader'
/var/www/sites/jupiter/app/models/ar_thesis.rb:109:in `block in from_thesis'
/var/www/sites/jupiter/app/models/ar_thesis.rb:108:in `each'
/var/www/sites/jupiter/app/models/ar_thesis.rb:108:in `from_thesis'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:111:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:118:in `block in each'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `map'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:110:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora
(See full trace by running task with --trace)
`
Same error, offending date now is '[1977?]'... ignoring values of length 7 now.

**Comment by mbarnett** [comment]
I think instead of length we'll need to take out the length check, try parsing it, and just rescue the ArgumentError if it crops up, because this data is clearly a hot mess

**Comment by ConnorSheremeta** [comment]
Success!
`Finished!`
Will open PR to ignore lengths 4 through 7 in coerce_value. I do not believe this should have an impact on valid dates.

**Comment by ConnorSheremeta** [comment]
New error now:

```
Migrating Items...
..rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Item type translation missing: en.activerecord.errors.models.ar_item.attributes.item_type.not_recognized
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:52:in `save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `block in save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:48:in `save!'
/var/www/sites/jupiter/app/models/ar_item.rb:124:in `block in from_item'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/app/models/ar_item.rb:115:in `from_item'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:103:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:118:in `block in each'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `map'
/var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:102:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora

```
Looking into it...

**Comment by ConnorSheremeta** [comment]
> New error now:
> 
> ```
> Migrating Items...
> ..rake aborted!
> ActiveRecord::RecordInvalid: Validation failed: Item type translation missing: en.activerecord.errors.models.ar_item.attributes.item_type.not_recognized
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:80:in `raise_validation_error'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:52:in `save!'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `block in save!'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `save!'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:48:in `save!'
> /var/www/sites/jupiter/app/models/ar_item.rb:124:in `block in from_item'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
> /var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
> /var/www/sites/jupiter/app/models/ar_item.rb:115:in `from_item'
> /var/www/sites/jupiter/lib/tasks/jupiter.rake:103:in `block (3 levels) in <top (required)>'
> /var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:118:in `block in each'
> /var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `map'
> /var/www/sites/jupiter/app/models/jupiter_core/deferred_simple_solr_query.rb:116:in `each'
> /var/www/sites/jupiter/lib/tasks/jupiter.rake:102:in `block (2 levels) in <top (required)>'
> Tasks: TOP => jupiter:get_me_off_of_fedora
> ```
> 
> Looking into it...

On a second run this didn't occur, hmmm. Going to run again once the pg db has been restored

**Comment by ConnorSheremeta** [comment]
Confirmed that the above error is caused from this item:

Item.find('4b3e0c51-33f7-4de9-97ad-d8bd298a8e92')
=> #<Item id: "4b3e0c51-33f7-4de9-97ad-d8bd298a8e92", visibility: "http://terms.library.ualberta.ca/embargo", owner: 270, record_created_at: 2018-05-09 16:23:21 UTC, hydra_noid: nil, date_ingested: 2018-05-09 16:23:21 UTC, title: "Fedora 4 OAI Provider Diagram", fedora3_uuid: nil, depositor: nil, alternative_title: "", doi: "doi:10.7939/R3JS9HP48", embargo_end_date: 2023-05-09 00:00:00 UTC, fedora3_handle: nil, ingest_batch: nil, northern_north_america_filename: nil, northern_north_america_item_id: nil, rights: nil, sort_year: 2018, visibility_after_embargo: "http://terms.library.ualberta.ca/public", embargo_history: nil, is_version_of: nil, member_of_paths: ["b50523c6-5037-40a0-b511-10aa6b17fe12/19e31dff-2f25-47bd-aa47-2a22017a1ade"], subject: ["Diagram", "Fedora 4", "OAI Provider"], creators: ["Charoenwattana, Piyapong"], unordered_creators: ["Charoenwattana, Piyapong"], contributors: nil, created: "2018-05-09", temporal_subjects: nil, spatial_subjects: nil, description: "Fedora 4 OAI provider architecture diagram", publisher: nil, languages: ["http://id.loc.gov/vocabulary/iso639-2/eng"], license: "http://creativecommons.org/licenses/by-nc/4.0/", item_type: "http://vivoweb.org/ontology/core#ConferencePaper", source: "", related_link: "", publication_status: nil>

Which there is an issue open to delete it in the console: https://github.com/ualbertalib/jupiter/issues/1636

**Comment by ConnorSheremeta** [comment]
Two new issues:

```
Preparing Attachments ...
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................rake aborted!
NoMethodError: undefined method `purge' for nil:NilClass
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activestorage-5.2.3/app/models/active_storage/attachment.rb:22:in `purge'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:61:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:59:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora
(See full trace by running task with --trace)
```
This one toesn't make sense because this error should've also occurred when retrieving the [blob_id](https://github.com/ualbertalib/jupiter/blob/integration_migration_phase1/lib/tasks/jupiter.rake#L60). It must somehow become nil between those two lines?

On a second run this error didn't occur so it can _probably_ be ignored, we could add a safe navigator operator just in case though.
___
```
Preparing Draft Item ...
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Language must exist
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:52:in `save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `block in save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `save!'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:48:in `save!'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:76:in `block (4 levels) in <top (required)>'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:74:in `block (3 levels) in <top (required)>'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/vendor/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/www/sites/jupiter/lib/tasks/jupiter.rake:68:in `block (2 levels) in <top (required)>'
Tasks: TOP => jupiter:get_me_off_of_fedora
```

One of the draft items doesn't contain a language, trying to find out which draft item is the culprit.

**Comment by mbarnett** [comment]
So the first one, it’s not that it becomes nil between lines, it’s that attachment.purge calls blob.purge: https://github.com/rails/rails/blob/v5.2.3/activestorage/app/models/active_storage/attachment.rb#L22 <https://github.com/rails/rails/blob/v5.2.3/activestorage/app/models/active_storage/attachment.rb#L22>, and you’ve already established that blob is nil because blob.present? is false. You really just want to destroy the attachment.

For the second one: Drafts are constantly being created, so this feels like a bit of a game of whack-a-mole. If you fix this, with fresher data or against Prod there’s going to be even newer drafts with even newer issues.

My suggestion for the language join table is that the save should bypass validations, to avoid this problem.
