### ISSUE TITLE
Production Deployment 

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#17]
- [ ] Fix thumb-nailing issue on production
- [ ] Go Live Checklist #224
- [ ] Completed user and object migration and audit
- [ ] Completed accessibility scan and fixes
- [ ] Completed user acceptance test and usability tests. 
- [ ] Performance testing, including stress testing with concurrent users
- [ ] Operationalize the application 
- [ ] https certificates
- [ ] skylight issues
- [x] thumbnails not appearing (generating?)

**Comment by weiweishi** [comment]
Folded into #224 close this ticket.
