### ISSUE TITLE
Update Admin interface to be consistent with mockups

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#211]
# Issue Description
Master issue to track all the changes.

All mockups can be found here: https://jupiter.mybalsamiq.com/projects/jupiter-admin/grid
# UPDATE STATUS
~After https://github.com/ualbertalib/jupiter/pull/236 gets merged~ (now merged) most of this functionality is now completed. 

## To do (Pre-production launch)
- [x] Faceting/Paginating/Searching/sorting of items on admin items view #263
- [ ] Need to provide Community dropdown (which is prefilled with how they got to the form). Admin should be able to move Collections to different Communities, etc.ticket: #512 <Communities Dropdown on Collection New/Edit Form (PR started here #239) >

## In Progress
- [x] Analytics #358 

## Post Production
- [ ] Edit static page
- [ ] Allow admin to deposit thesis 

______________________________________________________
Completed:
- [x] Faceting/Paginating/Searching/sorting of items on admin users detail #262 
- [x] Paginating/sorting of communities on communites and collections index view
- [x] Typeahead search for communties/collections on communties and collections index view #242 
- [x] Searching/Paginating/sorting of collections on community detail view
- [x] Faceting/Paginating/Searching/sorting of items on collection detail view
- Future work (comes later, after themeing/item deposit)
  - User's Draft Area
  - Navbar changes

# General
- [x] Navbar changes (can happen much later once we figure out themeing)
  - [x] No settings link, functionality doesn't exist
- [x] Sidebar is now just a top nav (mainly because of issues with sidebar displaying on mobile, it would take up the entire screen and you couldn't see the content or any change when switching links)
  - Should there be a special order here? Currently arranged somewhat random (of most used to least used)
- [x] General language/wording has been changed to be most simple (Removed all duplicated wording like "managed" everywhere, etc)
- [x] Removal of all shallow breadcrumbs (breadcrumbs that are one level deep which are just like "Admin > Static Pages")
- [x] Form buttons need to be right aligned (with cancel/secondary actions on left and save/primary  actions on right)

# Dashboard
- [x] No big changes here. Pretty much the same just some reordering of content (versions deemed least important, remove useless headers and HRs etc.
- [x] Sort recent activity of users by Last Seen At (now hooked up)

# Announcements
- [x] Now called "Announcements" instead of "Site Notifications" or "Site Messages"
- [x] Cleanup of language and duplication in current/previous announcements areas
- [x]  Previous Announcements area is now a searchable/sortable/paginated table
- [x] Displaying of Announcement should be below the navbar and be the same size (not in a bootstrap container) 
- [x] "Post" button placement should be right aligned

# Users
- [x] Filter and search should have labels (Filter has an "Filter By" Option, should be moved out as a label)
- [x] Replace "Updated At" column with "Last Seen At" (also this is the default sort now)

# User Detail
- [x] New "User's Draft Items" Area
  - [x] Stubbed in for now
- [x] Faceting/Searching/Sorting/Pagination of "User's Items"
- [x] "Impersonate" is now called "Login As User" (and "Stop Impersonating" is now "Logout As User")

# Communities and Collections
- [x] Nice typeahead search is required that searches across communities and collections
- [x] Need pagination and sorting of communities and collections
- [x] Stakeholders want accordions for list results. Perhaps investigate feasibility of this on mobile and desktop? Would be nice to have all accordions opened by default on desktop and closed on mobile. Currently mocked up as just a simple media list.

# Create/Edit Community
- [x] Use "Create" instead of "Add" or "New" or "Add New"
- [x] Have Edit title be "Edit {Community Name}" instead of just "Community" 
- [x] Nothing new except for button placements as noted above

# Community Detail
- [x] Searching/Sorting/Pagination of "Collections"

# Create/Edit Collection
- [x] Use "Create" instead of "Add" or "New" or "Add New"
- [x] Have Edit title be "Edit {Collection Name}" instead of just "Collection" 
- [x] Nothing new except for button placements as noted above

# Collection Detail
- [x] Faceting/Searching/Sorting/Pagination of "Collection Items"
- [ ] Has deposit item/thesis buttons for adding new items into this collection (should prefill the community/collection selection on the deposit form) #504 
  - [x] Added Deposit Item button on screen for now

# Items
- [x] Looks and acts just like "Search page" (minus communities and collections) #499 
- [ ] Has deposit item/thesis buttons for adding new items
  - [x] just added deposit item button for now
- [x] Use "Deposit Item" instead of "Add New Item"

**Comment by murny** [comment]
Closing this out, only things that are left is thesis deposit button, moving collections between communities and static page edit all which will have its own issues/epics/etc
