### ISSUE TITLE
Update Jupiter interface to be consistent with mockups

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#212]
# Issue Description

Similar to #211 but for non admin work

Master issue to track all the changes.

All mockups can be found here: https://jupiter.mybalsamiq.com/projects/jupiter/grid

## To-Do (pre-production):
- [x] Current Browse needs to be updated to reuse admins communities and collections view. Currently, they are quite different. Need to bring in the collapsible collections nested under all the communities.
- [x] Would suggest moving admin communities and collections views to non admin communities and collections (browse). Much like the community detail and collection detail views are currently being done with a over-writable breadcrumb partial.
- [x] Add handling of CCID protected items (should prompt users to login page, and redirect back to the item, or continue the download)

## In Progress:
Homepage
- [x] #101 

Static Pages
- [x] #413 (setup done. need to replace static content when it's ready)

## Post Production:
- [ ] Thesis Deposit

_________________________________________________
# General

- [x] Navbar changes for mobile/desktop
- [x] Removal of all shallow breadcrumbs (breadcrumbs that are one level deep which are just like "Home > Login")
- [x] Form buttons need to be right aligned (with cancel/secondary actions on left and save/primary actions on right)

# Login Page
Pretty much done except for:
- [x] SAML integration with ualberta
- [x] There was discussion regarding if having a page is even worth it? Login button in navbar could go directly to Ualberta Authentication etc. Requires future investigation.

# Browse
 Pretty much exactly the same as admin's community and collections, therefore:

- [x] Current Browse needs to be updated to reuse admins communities and collections view. Currently, they are quite different. Need to bring in the collapsible collections nested under all the communities.
- [x] Would suggest moving admin communities and collections views to non admin communities and collections (browse). Much like the community detail and collection detail views are currently being done with a over-writable breadcrumb partial.
- [x] Needs typeahead search for communties and collections
- [x] Needs pagination/sorting of list of communties for communties and collections
- [x] Searching/Paginating/sorting of collections on community detail view
- [x] Faceting/Paginating/Searching/sorting of items on collection detail view

# Search
Do work in current Search Epic #99  which displays mockups and outlines requirements (epic itself needs detailing added to it as still in a TODO state)

# User Dashboard
Essentially bring over the admin users detail view (with some very minor tweaks). URL should  be `/profile` or something and shows information depending on current user logged in. 

As with admin users detail view, features needing to be added are:
- [x] Needs faceting/searching/paginating/sorting of "My Items"
- [x] Implement "My Drafts"

Note: Once this is implemented/added need to update redirects in various places. 
 - When user logs in they should land on profile page or homepage?
 - When logging as user from admin, admin should be brought to the users profile page (currently it is the homepage)
 - etc?

# Item Deposit
Do work in current Item Deposit Epic #100  which displays mockups and outlines requirements (epic itself needs detailing added to it as still in a TODO state)

# Item Detail
- [x] Fix multi breadcrumbs - Community/Collection pairs are moved to a different section to be displayed
- [x] Add displaying and handling of multi-file items
- [x] Add arrangement of metadata (might be still under requirement gathering?)
- [x] Link metadata to search page (aka each author is a link to search for all items by said author, etc)
- [x] Handle thumbnailing and download of item

# Thesis Detail
- [x]  Much the same as Item Detail, Still need requirements (metadata) figured out and how data model looks like. Probably comes after Thesis Deposit

**Comment by murny** [comment]
Closing this out. Majority of this is done except for thesis deposit which is a different ticket
