### ISSUE TITLE
Google Scholar optimization

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#234]
To-do: breaking down the tasks

A summary of the Google Scholar work done on HydraNorth is [here](https://docs.google.com/document/d/1mVwcjHuTSg4srNDpVX4f9sIeIFske-MWzOg_oR41KYQ/edit). Our main areas of improvement were:

- [x] Modify download urls with .pdf
- [x]  Modify directory structure to place the file "below" the landing page
- [ ] ~~Browse by date (building on Sufia sitemap)~~
- [x]  Ensure date of publication is present
- [x]  Ensure abstracts are accessible
