### ISSUE TITLE
UI Refinement

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#238]
This is an epic to capture the work needed to polish the UI and the final touches to bring the design inline with the wireframes. It includes:
- [x] Regular user views #212 
- [x] Admin user view #211 
- [x] Date created facets should order by date instead of number of items #339 
- [x] Restrict number of facets rendered #305 
- [x] Facet ordering for search results #332 
- [x] Open "View" Item in new tab, and rename button #337 
- [x] Sort by date created instead of date uploaded #338 
- [x] Authorization Page? #97 
- [x] User profile dashboard #98 
- [x] Theme refinement https://github.com/ualbertalib/jupiter/issues/399

Mobile
- [x] Facets on mobile #230 
- [x] mobile nav menu #135

**Comment by murny** [comment]
Everything in ticket is now complete. Closing out.
