### ISSUE TITLE
Collection and Community

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#245]
Initial work was completed as part of the Admin feature epic #8 

Remaining work on collection and community include:
- [x] Create page for user view of collection and community #229 
- [x] Typehead search for communities/collections on community and collections index view #242 
- [x] Paginating/Sorting of items on the collection detail page #247 
- [x] Expanding list of collection on Community index page view (related to #246)
- [ ] Searching collections on the community detail page #243 (@sfbetz based on the ux testing, do we still want to do this?)

**Comment by cwant** [comment]
All of the checkmarks are filled and related issues are closed. This epic should likely be closed.
