### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#248]
Migration Plan:
Migration Content from HN to Jupiter:
The migration will take place in two stages:
## Initial data migration: 

It will migrate the production data on HN up until Feb 22, 2018 to Jupiter. The migration includes Communities, Collections, Generic Items, Theses, and Related Objects (FOMXL and technical metadata generated in HN) in following steps:
- [x] Production data dump from HN to gillingham (HN’s staging Fedora instance) - Done on Feb 22. 
- [x] Index the data from gillingham to sheff (Fedora 4.2’s triplestore) - Done on Feb 26
- [x] Create migration package from Sheff - Done on March 2
- [x] Remove all data migrated to era-beta
- [ ] Remigrate data
Documentation for migration is here: https://github.com/ualbertalib/di_internal/data-migration/Internal-Processes/HN-To-Jupiter-Migration.md
- [ ] Metadata team to evaluate data on mycombe/production triplestore server
- [ ] Any issues identified will be solved with rake tasks. 

## Issues identified:
(common error messages are defined in https://github.com/ualbertalib/di_internal/data-migration/Internal-Processes/HN-To-Jupiter-Migration.md)

- [ ] in migration package, some AccessRights triples are mapped to publication status:
```<http://server/fcrepo/rest/uat/2n/49/t2/91/2n49t2911> <http://purl.org/dc/terms/accessRights> <http://terms.library.ualberta.ca/draft> .```
@sfarnel @anayram @danydvd could you please check?
- [ ] Thumbnail generation for xslx file (temporarily stop generating thumbnails during migration for xslx files
- [ ] Several collections/communities were not migrated successfully - e.g. Northern North America Collection (44558t662)

## Second Stage:
Second stage of the migration will identify objects that were either changed on HN after Feb 22, 2018, or changed in tests on era-beta after Mar **, and then remigrate these objects:
- [ ] Halt any changes on HN 
- [ ] Get the update production data from HN
- [ ] Reindex the production data into triplestore
- [ ] Use the following query in HN's Rails Console to generate a list of objects that have been changed after Feb 22:
```
list = File.open('home/someuser/list_changed.txt', 'w+')
resp = ActiveFedora::SolrService.instance.conn.get "select", :params => {:q => "has_model_ssim:GenericFile AND system_modified_dtsi:[2018-02-21T23:59:59Z TO NOW]", :fl => "id"}
resp["response"]["docs"].each do |doc|
list.write(doc["id"])
end
list.close
```
- [ ] Use the following query to find a list of ERA objects that have been changed in era-beta (untested)
```resp = ActiveFedora::SolrService.instance.conn.get "select", :params => {:q => "-hydra_noid_ssim:[* TO *] AND has_model_ssim:IRItem AND system_modified_dtsi:[2018-02-21T23:59:59Z TO NOW]", :fl => "id"}```
```resp = ActiveFedora::SolrService.instance.conn.get "select", :params => {:q => "-hydra_noid_ssim:[* TO *] AND has_model_ssim:IRThesis AND system_modified_dtsi:[2018-02-21T23:59:59Z TO NOW]", :fl => "id"}```

- [ ] Generate an updated migration package (@anayram @sfarnel any way we can generate migration package for selective objects and not the complete set?)
- [ ] Remove the objects from the two lists
- [ ] Remigrate objects identified in these two lists (either from a complete migration package, or from the migration package only for these objects)
- [ ] remove beta data (any objects that don't have a hydra_noid value)

Work To-do:

- [x] Decision required re: Date that needs to be migrated
- [X] Decision required re: user info URI vs email address vs ID - user info in owner will be saved as id. 
- [x] Additional data model change, related to #100 
- [x] Adding data models for fedora3foxml and erastats1 #189
- [x] Handling order of the file in migration -based on file names
- [x] migration script for collection/community
- [x] migration script for item
- [x] migration script for thesis
- [x] migration script for file and fileset
- [x] migration script for related objects
- [ ] metadata review/item review 
- [x] user migration, with consolidated account when possible
- [x] handle zipped file during migration

**Comment by weiweishi** [comment]
Re: User migration:
-  Identified 235 email addresses that look like an alias (with ".", "-", "_" or other special characters in their ualberta email addresses). All are associated with their ccids.
-  Identified  38 users with hydranorth.ca email addresses and mapped them to correct ccid/email addresses. 
- Will migrate the rest of the users AS-IS, during the item migration.

**Comment by weiweishi** [comment]
Migration Content from HN to Jupiter:
The migration will take place in two stages:
1. Initial data migration: It will migrate the production data on HN up until Feb 22, 2018 to Jupiter. The migration includes Communities, Collections, Generic Items, Theses, and Related Objects (FOMXL and technical metadata generated in HN) in following steps:
-[x] Production data dump from HN to gillingham (HN’s staging Fedora instance) - Done on Feb 22. 
-[x] Index the data from gillingham to sheff (Fedora 4.2’s triplestore) - Done on Feb 26
-[x] Create migration package from Sheff - Done on March 2
-[x] Remove all data migrated to era-beta
-[ ] Remigrate data
Documentation for migration is here:
-[ ] Metadata team to evaluate data on mycombe/production triplestore server
-[ ] Any issues identified will be solved with rake tasks. 

Second stage of the migration will identify objects that were either changed on HN after Feb 22, 2018, or changed in tests on era-beta after Mar **, and then remigrate these objects:
-[ ] Halt any changes on HN 
-[ ] Get the update production data from HN
-[ ] Reindex the production data into triplestore
-[ ] Use the following query in HN's Rails Console to generate a list of objects that have been changed after Feb 22:
```
list = File.open('home/someuser/list_changed.txt', 'w+')
resp = ActiveFedora::SolrService.instance.conn.get "select", :params => {:q => "has_model_ssim:GenericFile AND system_modified_dtsi:[2018-02-21T23:59:59Z TO NOW]", :fl => "id"}
resp["response"]["docs"].each do |doc|
list.write(doc["id"])
end
list.close
```
-[ ] Use the following snippet of code to generate a list of objects that have been changed in era-beta - WIP
-[ ] Generate an updated migration package (@anayram @sfarnel any way we can generate migration package for selective objects and not the complete set?)
-[ ] Remove the objects from the two lists
-[ ] Remigrate objects identified in these two lists (either from a complete migration package, or from the migration package only for these objects)

**Comment by anayram** [comment]
@weiweishi yes, based on noids we can create a migration set in the triplestore to run the migration script and have a partial graph output.

**Comment by mbarnett** [comment]
Closing, since this happened a couple of years ago.
