### ISSUE TITLE
Refactoring Thoughts Tracking List

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#344]
- [x] Presenter for search/facet links and how they interact with translations and URI mappings. Extend facet presenter knowledge beyond just facets. (related: #334)  (related: https://github.com/ualbertalib/jupiter/pull/334/files#diff-cb1835837d7ece22b5100700894340f5R1. Don't like creating individual helpers & methods for every possible use -- `x_y_search_link` isn't scalable with more and more properties/types of things or readable in the view. Also don't like embedding it directly in a view. Needs DRYing). Concerned about this pattern getting repeated in the Thesis work creating more cleanup work/entrenchment. Need to find time to solve this ASAP.

- [x] Solve/centralize knowledge re: URI mappings code->URI and URI-> code conversions at multiple points in the code base. This probably implies URIs should be promoted to a type that encapsulates that knowledge.

- [ ] Is there a cleaner way to "chain" attributes/predicates together that simply contain transformations of another's data? Current use cases: memberOf/member_of_paths and creators/authorList. Plays into potential spikes in the direction of "replayability" of unlocked blocks if we need to keep Fedora in a less prominent position in the stack (write one half of the chain in one datastore, the other in the other). (related: #333)

- [ ] Transparent pagination of large Solr result documents -- `Item.all` with > 40k items in the result page -> internally break it into limit/offset calls of maybe 1000 results each and pull the next 1000 as needed during iteration. (related: #340)

- [ ] Chris notes that these(https://github.com/ualbertalib/jupiter/blob/master/app/models/jupiter_core/locked_ldp_object.rb#L480) run once per inheritance level. They should be moved to a common AF superclass so they're not constantly redefined.

**Comment by mbarnett** [comment]
Most of this is no longer applicable. Closing.
