### ISSUE TITLE
OAI Implementation in Fedora 4.7 with Jupiter

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#376]
This is to capture the work needed for the OAI implementation in Fedora 4.7 with Jupiter. 
To-Do:
- [ ] documentation for deployment
  - [ ] Docker environment (https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/27)
  - [ ] Production (https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/28)
  - [x] [Release Notes (including: deployment, build, architecture)](https://github.com/ualbertalib/fcrepo4-oaiprovider/blob/fcrepo_4.7.4/RELEASE_NOTES.md)

Ongoing:
- [x] in OAI map current data model to 
  - [x] ETDMS
    - [x] core properties
    - [x] file information(https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/26)
  - [x] OAI-ORE
    - [x] core properties
    - [x] file information(https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/26)
  - [x] DC
    - [x] Initial mapping compete
- [x] regression testing OAI
    - [x] Bug related to `from` & `until` date parameters (https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/25)
    - [x] bug/questions flowing from first round of testing (https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/29)
- [ ] Dockerhub integration with Jupiter (https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/27)

Testing (gillingham2):
  - [ ] verify assumptions (https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/30)
  - [x] test with production data
  - [x] test deployment
    - [x] check URL paths in output for conformance with Jupiter (e.g., oai.xml)

Completed: 
- [x] set up OAI provider to work with Fedora 4.7
- [x] Updated namespaces to conform with Jupiter data model
- [x] manage the multiple community/collection pairs in sets
- [x] enable indexing and performance tweaks in config

@jefferya could you please update the To-Dos and the Completed sections, and add additional tasks if I've missed any?

**Comment by jefferya** [comment]
@weiweishi I've updated, broke apart some items and added a couple others to record progress. I'll try to revise a bit more on Monday. A summary, the main remaining piece is gathering the file related information, then testing in the Jupiter Docker infrastructure.

**Comment by weiweishi** [comment]
I believe this is completed. We can reopen new tickets for anything missing if needed.
