### ISSUE TITLE
Jupiter Triplestore

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#377]
To capture work needed for jupiter's triplestore setup
@piyapongch Could you please review and capture what's been done, and what needs to be done in this list?

Ongoing:
- [x] Karaf configuration
- [x] Indexing process
- [x] Test deployment

To do:
- [x] ansible playbook development
- [x] deploy to production environment
 
Completed
- [x] Infrastructure set up for staging and production env. 
- [x] Karaf installation
- [x] Blazegraph installation
- [x] Live update with Fedora 4.7

**Comment by weiweishi** [comment]
New documentation for triplestore configuration is at:
https://github.com/ualbertalib/di_internal/tree/triplestore/Triplestore

**Comment by weiweishi** [comment]
I believe this is completed? @piyapongch
