### ISSUE TITLE
Jupiter: Thesis Deposit

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#709]
Requirements:
- [ ] Allow admin users to deposit/edit theses with associated specialized metadata as outlined here:
https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_thesis.md
- [ ] No need to show item type on deposit/edit
- [ ] Can only deposit into Graduate Studies and Research, Faculty of / Theses and Dissertations
and St. Stephen's community/collections
- [ ] Graduation date should also be treated as a controlled vocabulary. Proceed with two dropdowns: optional: Spring or Fall + required year dropdown. 
- [ ] It uses a default license. Language as below:
"This thesis is made available by the University of Alberta Libraries with permission of the copyright owner solely for non-commercial purposes. This thesis, or any portion thereof, may not otherwise be copied or reproduced without the written consent of the copyright owner, except to the extent permitted by Canadian copyright law."
- [ ] Doesn't need to have a CCID protected option for visibility

Wireframes:
![Image of Thesis Deposit Mockup](https://jupiter.mybalsamiq.com/mockups/6178693.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Deposit%20-%20Thesis

**Comment by sfarnel** [comment]
Thanks @weiweishi 
Theses can be deposited into any of the three St. Stephen's College collections.
Graduation date is tricky. Any new UA theses will have it in the form noted in the data dictionary, but legacy UA and St. Stephen's new theses may or may not. If there is a way to handle this that would be great. Copying in @danydvd and @anayram so we can think through how best to express this in the data dictionary

**Comment by weiweishi** [comment]
thanks @sfarnel 
this seems to be in contradiction with the comments on the wireframe:
" All theses deposited by this form should go into FGSR community --> Theses and dissertations collection. There may be these that don't belong to that community but will only be deposited via batch. "

So I just wanted to clarify.

**Comment by sfarnel** [comment]
Thanks @weiweishi @leahvanderjagt can confirm whether or not a St. Stephen's would ever come not in a batch. Perhaps not!

**Comment by weiweishi** [comment]
Confirmed with @leahvanderjagt that admin should be able to deposit into both FGSR and St. Stephen's College community and their collections.

**Comment by murny** [comment]
Is there a defined list of required fields for thesis on the form?

According to here the properties that are required in the data dictionary:
https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_thesis.md#required

It's basically just

- title
- dissertant (author/creator)
- graduation date
- sortYear (which is derived from graduation date)
- community/collection
- type ( but type will always be thesis)

I would have assumed language, subjects & keywords, license & rights (even though every thesis has the same license) and Abstract/description (as this is indicated on the mockups) to be required?

Then assuming the rest are optional (degree/department/supervisor/etc)

Can anyone give some clarification here? Thanks!

**Comment by murny** [comment]
This is exclusively for the thesis deposit form. 

So they will only fail validations when creating a new thesis or editing an existing thesis (forcing a user to update old thesis to match new requirements, aka add an abstract/language/etc) via thesis deposit form. 

So if this might prove to be a problem then better to make these optional in the thesis deposit form.

**Comment by weiweishi** [comment]
So the validation will only be enforced on the UI, not on the data model level? This is probably different from the original meaning of the "required" in the data dictionary.   Thanks for the clarification. 

My impression is this might be an issue for editing old thesis? when if we want to add/edit some info on these old theses but don't have all the required info? 

@leahvanderjagt how often do you see the old ProQuest theses to be modified through the UI? My sense is it doesn't happen often but does happen occasionally in the past, for an author name change etc. How important do you feel we should have validation on the thesis deposit form for admin, to make sure new deposit has all the required information we need?

**Comment by murny** [comment]
According to data dictionary, there will be two additional date fields, [Date Accepted](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_thesis.md#dctermsdateaccepted) and [Date Submitted](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_thesis.md#dctermsdatesubmitted) will be on the deposit thesis form? Is this correct?

**Comment by sfarnel** [comment]
Thanks @murny and @weiweishi for this discussion! When we worked this out with @leahvanderjagt she wanted the number of required elements to be very minimal for the form because theses rarely get deposited in this way, and when they do we often have very little information, as you've observed. This was hashed out in a meeting and info is in ualbertalib/metadata#125 and the data dictionary. @murny those two fields are on the form but optional. Hope this helps!

**Comment by weiweishi** [comment]
Deployed to production. Demo-ed to @abombak . Will close this ticket.
