### ISSUE TITLE
Item View

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#86]
Updated Nov 14

To-do:

- [x] file download from the item view page #88 
- [x] data presented on item view should be in line with the data dictionary #251 
- [x] fields are presented as in the mockup #334  
- [x] data presented on thesis's item view should be in line with the data dictionary #336 
- [x] multifile download #90 

Wishlist:
- [ ] Viewers #91 

### Mockup for Item Detail:
![Image of Item Detail Mockup](https://jupiter.mybalsamiq.com/mockups/6069946.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Item%20Detail
### Mockup for Thesis Detail:
![Image of Thesis Detail Mockup](https://jupiter.mybalsamiq.com/mockups/6250975.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Thesis%20Detail
