### ISSUE TITLE
Port sitemap work

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#9]
Caching currently lasts 24 hours from the first request to /sitemap.xml, although we can raise or lower this as desired. My back-of-the envelope math says it will take around 45 seconds to respond to the first request assuming about 45k items in the repository. A nightly cron task to curl the URL would eliminate any lag for most users.

- [x] Get the modified date indexed into Solr
- [x]  Theses.
- [x]  Item visibility (filter out private items)
- [x]  Add a static robots.txt file?
- [x]  Other requirements from Google Scholar requirements: #234 
- [x]  Change SitemapPolicy to simply inherit from ApplicationPolicy.
- [x]  Add an application specific property on fileset to include hash, file size, and mimetype information.
